// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taxi_Managment_System_DAL.Data;

#nullable disable

namespace Taxi_Managment_System.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Cab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CarModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manufacture_year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cab", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5165210-6c72-440a-9f8e-f3e9808cb391"),
                            Active = true,
                            CarModel = "911",
                            LicensePlate = "un6loh",
                            Manufacture_year = 1732968761
                        },
                        new
                        {
                            Id = new Guid("1ff34e0d-4301-4d44-9b9c-8a883c55871a"),
                            Active = false,
                            CarModel = "Model 3",
                            LicensePlate = "w59jw7",
                            Manufacture_year = 855284559
                        },
                        new
                        {
                            Id = new Guid("d88926df-d274-4105-b2e0-8d0f35233ab6"),
                            Active = true,
                            CarModel = "Golf",
                            LicensePlate = "od9fj4",
                            Manufacture_year = 1889786543
                        },
                        new
                        {
                            Id = new Guid("a3f32cf7-cde0-40d4-aa40-31798c1b8c5b"),
                            Active = false,
                            CarModel = "Volt",
                            LicensePlate = "j38n52",
                            Manufacture_year = 691530179
                        },
                        new
                        {
                            Id = new Guid("5bda64d4-1d57-414f-a61c-69f09cdc2182"),
                            Active = true,
                            CarModel = "Ranchero",
                            LicensePlate = "9ea3zi",
                            Manufacture_year = 794028919
                        },
                        new
                        {
                            Id = new Guid("2e6fad70-73c8-4d09-b0ae-6da1b0a73b43"),
                            Active = true,
                            CarModel = "Taurus",
                            LicensePlate = "tek4dg",
                            Manufacture_year = 1864333650
                        },
                        new
                        {
                            Id = new Guid("20a56bed-f0b6-4000-9bfa-01d2b2db7bc7"),
                            Active = true,
                            CarModel = "Model 3",
                            LicensePlate = "8m3sey",
                            Manufacture_year = 28987858
                        },
                        new
                        {
                            Id = new Guid("17058a79-c06f-4954-ac65-d817cb5109cc"),
                            Active = false,
                            CarModel = "Altima",
                            LicensePlate = "mrz9fk",
                            Manufacture_year = 1833086749
                        },
                        new
                        {
                            Id = new Guid("49fabbc3-d04d-4317-8337-dc48ebe4f82a"),
                            Active = true,
                            CarModel = "Challenger",
                            LicensePlate = "88q0nc",
                            Manufacture_year = 1245493851
                        },
                        new
                        {
                            Id = new Guid("4e0209c1-f9b5-4612-9acd-d68d16935549"),
                            Active = true,
                            CarModel = "Malibu",
                            LicensePlate = "jlm3x3",
                            Manufacture_year = 830116241
                        },
                        new
                        {
                            Id = new Guid("b9be0b98-f0e1-4a6e-930c-c26f8b5c44a0"),
                            Active = true,
                            CarModel = "Corvette",
                            LicensePlate = "7ppp49",
                            Manufacture_year = 1154209915
                        },
                        new
                        {
                            Id = new Guid("b99c126b-d873-425a-a056-41ed749a9cc8"),
                            Active = false,
                            CarModel = "XTS",
                            LicensePlate = "onnmfl",
                            Manufacture_year = 1979092028
                        },
                        new
                        {
                            Id = new Guid("3a7420d0-8686-4dc4-b321-d0dc879c452c"),
                            Active = false,
                            CarModel = "Silverado",
                            LicensePlate = "c9d3nk",
                            Manufacture_year = 400758562
                        },
                        new
                        {
                            Id = new Guid("bdceb7ab-4b1b-46e5-8467-80afe6bcb0a2"),
                            Active = true,
                            CarModel = "Model S",
                            LicensePlate = "5yker7",
                            Manufacture_year = 1559728135
                        },
                        new
                        {
                            Id = new Guid("839f93a0-7e81-4cf6-9657-3e7a7f61e1bb"),
                            Active = false,
                            CarModel = "Element",
                            LicensePlate = "53yjuf",
                            Manufacture_year = 1960941622
                        },
                        new
                        {
                            Id = new Guid("aa8519ef-a257-4cd2-8fdd-f506ef2da9e3"),
                            Active = true,
                            CarModel = "Challenger",
                            LicensePlate = "dk1f95",
                            Manufacture_year = 1973978347
                        },
                        new
                        {
                            Id = new Guid("334a5e53-989c-4486-9d07-d6ffccb609f8"),
                            Active = false,
                            CarModel = "Focus",
                            LicensePlate = "swnjy8",
                            Manufacture_year = 1391304054
                        },
                        new
                        {
                            Id = new Guid("2f239779-4aa6-4e8a-a9b2-8d487b0097c9"),
                            Active = true,
                            CarModel = "Wrangler",
                            LicensePlate = "1kqdw4",
                            Manufacture_year = 1100995239
                        },
                        new
                        {
                            Id = new Guid("b749b2a6-3fb0-448d-b878-b5da09592d7a"),
                            Active = false,
                            CarModel = "Mustang",
                            LicensePlate = "pckqwt",
                            Manufacture_year = 314166503
                        },
                        new
                        {
                            Id = new Guid("da917976-0cee-4ea9-b36d-2d4aedc34f37"),
                            Active = true,
                            CarModel = "El Camino",
                            LicensePlate = "yz8jbp",
                            Manufacture_year = 1099056322
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.CabRide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressDestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressStartingPoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<Guid>("PaymentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("RideEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RideStartTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("ShiftId");

                    b.ToTable("cab_ride", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f45fcc9a-3d21-4614-8255-85de9b7d1e59"),
                            AddressDestination = "2629 Herzog Club",
                            AddressStartingPoint = "418 Rosenbaum Drive",
                            Canceled = true,
                            PaymentTypeId = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            Price = 62.23m,
                            RideEndTime = new DateTime(2022, 8, 11, 19, 2, 37, 140, DateTimeKind.Local).AddTicks(4189),
                            RideStartTime = new DateTime(2022, 8, 11, 18, 57, 59, 581, DateTimeKind.Local).AddTicks(4202),
                            ShiftId = new Guid("8633f0ad-bb06-4172-b77e-5a5f4ff5c6f0")
                        },
                        new
                        {
                            Id = new Guid("2dc3dc15-be66-4fdb-9897-573849ceae43"),
                            AddressDestination = "115 Alia Centers",
                            AddressStartingPoint = "469 Kristin Turnpike",
                            Canceled = false,
                            PaymentTypeId = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            Price = 907.04m,
                            RideEndTime = new DateTime(2022, 10, 17, 16, 15, 6, 524, DateTimeKind.Local).AddTicks(617),
                            RideStartTime = new DateTime(2022, 10, 17, 16, 11, 15, 244, DateTimeKind.Local).AddTicks(8077),
                            ShiftId = new Guid("3e900077-4087-4b66-8578-9dd2b562fb51")
                        },
                        new
                        {
                            Id = new Guid("c0bb6831-a382-4ba3-9642-8f3974b08af8"),
                            AddressDestination = "06327 Joseph Ville",
                            AddressStartingPoint = "5734 Larissa Course",
                            Canceled = false,
                            PaymentTypeId = new Guid("985e82da-34d5-4312-b988-f61109671c7c"),
                            Price = 937.56m,
                            RideEndTime = new DateTime(2022, 8, 12, 8, 42, 59, 383, DateTimeKind.Local).AddTicks(1249),
                            RideStartTime = new DateTime(2022, 8, 12, 8, 40, 48, 406, DateTimeKind.Local).AddTicks(9651),
                            ShiftId = new Guid("8633f0ad-bb06-4172-b77e-5a5f4ff5c6f0")
                        },
                        new
                        {
                            Id = new Guid("f9d3665f-2743-49d9-b7e1-de9551c9ba0e"),
                            AddressDestination = "83949 Bins Walks",
                            AddressStartingPoint = "43799 Lambert Court",
                            Canceled = false,
                            PaymentTypeId = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            Price = 785.22m,
                            RideEndTime = new DateTime(2022, 11, 10, 10, 8, 29, 900, DateTimeKind.Local).AddTicks(7954),
                            RideStartTime = new DateTime(2022, 11, 10, 9, 40, 41, 646, DateTimeKind.Local).AddTicks(8934),
                            ShiftId = new Guid("be5527a5-b550-4682-8f1b-5abbe1e62dc9")
                        },
                        new
                        {
                            Id = new Guid("369373ed-c6ff-4284-8048-d4c145f1e9b4"),
                            AddressDestination = "62940 Lynch Union",
                            AddressStartingPoint = "6560 Fatima Islands",
                            Canceled = false,
                            PaymentTypeId = new Guid("985e82da-34d5-4312-b988-f61109671c7c"),
                            Price = 66.92m,
                            RideEndTime = new DateTime(2022, 11, 13, 12, 25, 13, 179, DateTimeKind.Local).AddTicks(4317),
                            RideStartTime = new DateTime(2022, 11, 13, 12, 14, 32, 151, DateTimeKind.Local).AddTicks(3413),
                            ShiftId = new Guid("3e900077-4087-4b66-8578-9dd2b562fb51")
                        },
                        new
                        {
                            Id = new Guid("ef663dd2-e114-4a47-b67e-80281d54f138"),
                            AddressDestination = "74765 Luettgen Extensions",
                            AddressStartingPoint = "6368 Zachery Motorway",
                            Canceled = true,
                            PaymentTypeId = new Guid("985e82da-34d5-4312-b988-f61109671c7c"),
                            Price = 444.34m,
                            RideEndTime = new DateTime(2022, 6, 18, 20, 47, 38, 345, DateTimeKind.Local).AddTicks(2966),
                            RideStartTime = new DateTime(2022, 6, 18, 20, 43, 3, 493, DateTimeKind.Local).AddTicks(7177),
                            ShiftId = new Guid("1a59f6e7-ba15-4f60-9ba1-210a1641bc99")
                        },
                        new
                        {
                            Id = new Guid("73f727ed-72f9-476b-a69e-526b0792c433"),
                            AddressDestination = "25099 Theodore Coves",
                            AddressStartingPoint = "16744 White Isle",
                            Canceled = true,
                            PaymentTypeId = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            Price = 646.43m,
                            RideEndTime = new DateTime(2022, 7, 13, 13, 39, 40, 891, DateTimeKind.Local).AddTicks(4403),
                            RideStartTime = new DateTime(2022, 7, 13, 13, 25, 15, 343, DateTimeKind.Local).AddTicks(7446),
                            ShiftId = new Guid("8633f0ad-bb06-4172-b77e-5a5f4ff5c6f0")
                        },
                        new
                        {
                            Id = new Guid("10adaefe-e65a-4149-8c21-96dd7a9a1078"),
                            AddressDestination = "523 Gusikowski Way",
                            AddressStartingPoint = "8399 Cormier Row",
                            Canceled = true,
                            PaymentTypeId = new Guid("985e82da-34d5-4312-b988-f61109671c7c"),
                            Price = 578.61m,
                            RideEndTime = new DateTime(2022, 11, 22, 12, 32, 13, 784, DateTimeKind.Local).AddTicks(8656),
                            RideStartTime = new DateTime(2022, 11, 22, 12, 10, 50, 854, DateTimeKind.Local).AddTicks(6304),
                            ShiftId = new Guid("e68a650b-26e9-4e44-be09-1d50833329d0")
                        },
                        new
                        {
                            Id = new Guid("1b1c8b84-4042-4b0e-a5bf-3d54bd7d06b5"),
                            AddressDestination = "9959 Borer Rapids",
                            AddressStartingPoint = "48701 Hallie Park",
                            Canceled = true,
                            PaymentTypeId = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            Price = 312.17m,
                            RideEndTime = new DateTime(2023, 4, 15, 18, 1, 36, 451, DateTimeKind.Local).AddTicks(6821),
                            RideStartTime = new DateTime(2023, 4, 15, 17, 40, 0, 132, DateTimeKind.Local).AddTicks(9910),
                            ShiftId = new Guid("8633f0ad-bb06-4172-b77e-5a5f4ff5c6f0")
                        },
                        new
                        {
                            Id = new Guid("9070c2d9-d6e9-4895-bd6a-5eeea2f3b074"),
                            AddressDestination = "1011 Armando Mills",
                            AddressStartingPoint = "919 Bernita Curve",
                            Canceled = false,
                            PaymentTypeId = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            Price = 327.37m,
                            RideEndTime = new DateTime(2023, 4, 9, 21, 51, 40, 601, DateTimeKind.Local).AddTicks(5380),
                            RideStartTime = new DateTime(2023, 4, 9, 21, 40, 33, 576, DateTimeKind.Local).AddTicks(9592),
                            ShiftId = new Guid("be5527a5-b550-4682-8f1b-5abbe1e62dc9")
                        },
                        new
                        {
                            Id = new Guid("3b3598ce-de43-4bba-8b09-3605f202ed8a"),
                            AddressDestination = "85489 Adolph Station",
                            AddressStartingPoint = "624 Auer Station",
                            Canceled = false,
                            PaymentTypeId = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            Price = 609.83m,
                            RideEndTime = new DateTime(2022, 8, 8, 1, 39, 31, 715, DateTimeKind.Local).AddTicks(970),
                            RideStartTime = new DateTime(2022, 8, 8, 1, 38, 21, 82, DateTimeKind.Local).AddTicks(6345),
                            ShiftId = new Guid("453baad2-d6b8-449c-87ad-1e30755ce5f0")
                        },
                        new
                        {
                            Id = new Guid("1e1c7fb6-7997-4297-b829-ee818635329a"),
                            AddressDestination = "98916 Gutmann Ports",
                            AddressStartingPoint = "8273 Collins Fort",
                            Canceled = false,
                            PaymentTypeId = new Guid("0eff2385-86f2-4113-bb02-3b9d382083db"),
                            Price = 64.85m,
                            RideEndTime = new DateTime(2023, 5, 20, 2, 3, 46, 333, DateTimeKind.Local).AddTicks(5745),
                            RideStartTime = new DateTime(2023, 5, 20, 1, 35, 48, 116, DateTimeKind.Local).AddTicks(7486),
                            ShiftId = new Guid("3453203c-ed99-4fb1-9f36-62a4b0f788cf")
                        },
                        new
                        {
                            Id = new Guid("7a2cb453-04e3-47ab-816f-ee492ed8aed8"),
                            AddressDestination = "0682 Johnston Lodge",
                            AddressStartingPoint = "132 Earline Unions",
                            Canceled = true,
                            PaymentTypeId = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            Price = 949.18m,
                            RideEndTime = new DateTime(2022, 7, 3, 5, 20, 52, 643, DateTimeKind.Local).AddTicks(7957),
                            RideStartTime = new DateTime(2022, 7, 3, 5, 16, 23, 668, DateTimeKind.Local).AddTicks(5027),
                            ShiftId = new Guid("9b94d825-fd94-43e3-997d-cde536917e52")
                        },
                        new
                        {
                            Id = new Guid("e5a32545-6ae7-4957-a4e4-8e7ef3655c89"),
                            AddressDestination = "6442 Anna Rapids",
                            AddressStartingPoint = "13968 Lockman Point",
                            Canceled = false,
                            PaymentTypeId = new Guid("0eff2385-86f2-4113-bb02-3b9d382083db"),
                            Price = 459.49m,
                            RideEndTime = new DateTime(2022, 6, 16, 20, 20, 30, 556, DateTimeKind.Local).AddTicks(8287),
                            RideStartTime = new DateTime(2022, 6, 16, 19, 57, 8, 721, DateTimeKind.Local).AddTicks(97),
                            ShiftId = new Guid("3453203c-ed99-4fb1-9f36-62a4b0f788cf")
                        },
                        new
                        {
                            Id = new Guid("8a1e2689-36f2-4dd1-886b-4f192f6db7f3"),
                            AddressDestination = "5483 Dagmar Circle",
                            AddressStartingPoint = "89871 Boehm Glen",
                            Canceled = true,
                            PaymentTypeId = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            Price = 730.08m,
                            RideEndTime = new DateTime(2023, 1, 22, 13, 17, 50, 131, DateTimeKind.Local).AddTicks(9394),
                            RideStartTime = new DateTime(2023, 1, 22, 12, 49, 14, 536, DateTimeKind.Local).AddTicks(8702),
                            ShiftId = new Guid("6601fc2b-30e8-4aa9-b84d-655484c7d375")
                        },
                        new
                        {
                            Id = new Guid("acf64304-6347-464e-a1bc-b71168c5dcf1"),
                            AddressDestination = "1773 Hoppe Mews",
                            AddressStartingPoint = "977 Herzog Inlet",
                            Canceled = true,
                            PaymentTypeId = new Guid("0eff2385-86f2-4113-bb02-3b9d382083db"),
                            Price = 619.04m,
                            RideEndTime = new DateTime(2023, 1, 2, 2, 7, 24, 516, DateTimeKind.Local).AddTicks(5241),
                            RideStartTime = new DateTime(2023, 1, 2, 1, 43, 5, 353, DateTimeKind.Local).AddTicks(7293),
                            ShiftId = new Guid("6601fc2b-30e8-4aa9-b84d-655484c7d375")
                        },
                        new
                        {
                            Id = new Guid("d3db81d3-4e36-45ca-b8ea-51495ecb91dd"),
                            AddressDestination = "9725 Ledner Crest",
                            AddressStartingPoint = "77016 Douglas Fort",
                            Canceled = true,
                            PaymentTypeId = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            Price = 97.34m,
                            RideEndTime = new DateTime(2022, 12, 13, 20, 50, 25, 196, DateTimeKind.Local).AddTicks(2183),
                            RideStartTime = new DateTime(2022, 12, 13, 20, 28, 5, 530, DateTimeKind.Local).AddTicks(4260),
                            ShiftId = new Guid("416d4501-2004-4d48-ac1a-c83422a31563")
                        },
                        new
                        {
                            Id = new Guid("b3118988-0bc1-42a6-bd2b-c1fb968a7743"),
                            AddressDestination = "08638 Renner Ridge",
                            AddressStartingPoint = "2633 Jessie Fords",
                            Canceled = false,
                            PaymentTypeId = new Guid("0eff2385-86f2-4113-bb02-3b9d382083db"),
                            Price = 85.82m,
                            RideEndTime = new DateTime(2022, 6, 11, 17, 38, 9, 88, DateTimeKind.Local).AddTicks(5089),
                            RideStartTime = new DateTime(2022, 6, 11, 17, 26, 44, 611, DateTimeKind.Local).AddTicks(6267),
                            ShiftId = new Guid("6405f468-ab27-4777-b47f-6f4279823e87")
                        },
                        new
                        {
                            Id = new Guid("2b71ef8e-dc62-4090-b859-1d64b12eeef8"),
                            AddressDestination = "7838 Dario Views",
                            AddressStartingPoint = "06346 Doyle Extensions",
                            Canceled = false,
                            PaymentTypeId = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            Price = 676.29m,
                            RideEndTime = new DateTime(2023, 6, 2, 2, 3, 21, 228, DateTimeKind.Local).AddTicks(7115),
                            RideStartTime = new DateTime(2023, 6, 2, 1, 40, 25, 544, DateTimeKind.Local).AddTicks(4780),
                            ShiftId = new Guid("6405f468-ab27-4777-b47f-6f4279823e87")
                        },
                        new
                        {
                            Id = new Guid("75855a1c-a2a7-4148-abfe-4dd74258f42d"),
                            AddressDestination = "5495 Bradtke Port",
                            AddressStartingPoint = "51399 Lesly Roads",
                            Canceled = false,
                            PaymentTypeId = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            Price = 229.82m,
                            RideEndTime = new DateTime(2023, 1, 14, 1, 0, 23, 987, DateTimeKind.Local).AddTicks(5348),
                            RideStartTime = new DateTime(2023, 1, 14, 0, 39, 29, 174, DateTimeKind.Local).AddTicks(1335),
                            ShiftId = new Guid("7494d324-b215-48e4-828b-c0216d232b6d")
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.CabRideStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CabRideId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StatusTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CabRideId");

                    b.HasIndex("StatusId");

                    b.ToTable("cab_ride_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("97cfa1c2-10f1-4499-bf5b-a1aee662f80e"),
                            CabRideId = new Guid("2dc3dc15-be66-4fdb-9897-573849ceae43"),
                            StatusId = new Guid("1322b7a1-90bd-475f-bdc7-30a308b4bb61"),
                            StatusTime = new DateTime(2022, 11, 2, 16, 41, 23, 416, DateTimeKind.Local).AddTicks(3955)
                        },
                        new
                        {
                            Id = new Guid("37fbef7f-2587-4391-9752-b2169e624aba"),
                            CabRideId = new Guid("1b1c8b84-4042-4b0e-a5bf-3d54bd7d06b5"),
                            StatusId = new Guid("154ea15b-a524-40a6-89ff-2cd5efb69aed"),
                            StatusTime = new DateTime(2022, 12, 13, 20, 4, 35, 166, DateTimeKind.Local).AddTicks(9902)
                        },
                        new
                        {
                            Id = new Guid("1c5d9197-50fa-4ebb-9ad6-0244c3bdf547"),
                            CabRideId = new Guid("c0bb6831-a382-4ba3-9642-8f3974b08af8"),
                            StatusId = new Guid("51b4484f-6d43-4dfd-bf70-6febcdbb2522"),
                            StatusTime = new DateTime(2023, 3, 2, 21, 11, 44, 784, DateTimeKind.Local).AddTicks(5387)
                        },
                        new
                        {
                            Id = new Guid("bfff398a-9e80-475d-9095-4461d0d496af"),
                            CabRideId = new Guid("73f727ed-72f9-476b-a69e-526b0792c433"),
                            StatusId = new Guid("51b4484f-6d43-4dfd-bf70-6febcdbb2522"),
                            StatusTime = new DateTime(2023, 3, 9, 19, 32, 53, 54, DateTimeKind.Local).AddTicks(6298)
                        },
                        new
                        {
                            Id = new Guid("3b6944f8-a888-4850-b6b0-bd16e325974a"),
                            CabRideId = new Guid("9070c2d9-d6e9-4895-bd6a-5eeea2f3b074"),
                            StatusId = new Guid("51b4484f-6d43-4dfd-bf70-6febcdbb2522"),
                            StatusTime = new DateTime(2022, 12, 25, 12, 17, 11, 599, DateTimeKind.Local).AddTicks(7400)
                        },
                        new
                        {
                            Id = new Guid("998fe270-e059-4064-a635-3a4bec456e29"),
                            CabRideId = new Guid("f9d3665f-2743-49d9-b7e1-de9551c9ba0e"),
                            StatusId = new Guid("51b4484f-6d43-4dfd-bf70-6febcdbb2522"),
                            StatusTime = new DateTime(2023, 3, 25, 11, 30, 52, 187, DateTimeKind.Local).AddTicks(909)
                        },
                        new
                        {
                            Id = new Guid("d1479dbd-aaca-4c0e-87ab-5ac281be4008"),
                            CabRideId = new Guid("c0bb6831-a382-4ba3-9642-8f3974b08af8"),
                            StatusId = new Guid("154ea15b-a524-40a6-89ff-2cd5efb69aed"),
                            StatusTime = new DateTime(2022, 7, 15, 10, 20, 34, 119, DateTimeKind.Local).AddTicks(5422)
                        },
                        new
                        {
                            Id = new Guid("eb9ecd3b-b801-403f-bcca-c123ba491b0d"),
                            CabRideId = new Guid("2dc3dc15-be66-4fdb-9897-573849ceae43"),
                            StatusId = new Guid("51b4484f-6d43-4dfd-bf70-6febcdbb2522"),
                            StatusTime = new DateTime(2022, 8, 12, 13, 7, 5, 162, DateTimeKind.Local).AddTicks(2403)
                        },
                        new
                        {
                            Id = new Guid("489e0666-a14d-4515-b70f-dafa527b1645"),
                            CabRideId = new Guid("9070c2d9-d6e9-4895-bd6a-5eeea2f3b074"),
                            StatusId = new Guid("154ea15b-a524-40a6-89ff-2cd5efb69aed"),
                            StatusTime = new DateTime(2022, 6, 10, 1, 1, 23, 150, DateTimeKind.Local).AddTicks(4898)
                        },
                        new
                        {
                            Id = new Guid("695f7b5f-e653-4222-b28b-dce5928c6958"),
                            CabRideId = new Guid("9070c2d9-d6e9-4895-bd6a-5eeea2f3b074"),
                            StatusId = new Guid("1322b7a1-90bd-475f-bdc7-30a308b4bb61"),
                            StatusTime = new DateTime(2022, 10, 20, 6, 14, 5, 797, DateTimeKind.Local).AddTicks(3628)
                        },
                        new
                        {
                            Id = new Guid("c660923d-33d8-4127-a79f-c46fb3573923"),
                            CabRideId = new Guid("1e1c7fb6-7997-4297-b829-ee818635329a"),
                            StatusId = new Guid("b370867a-2261-42eb-9b7b-2fd6bd26a224"),
                            StatusTime = new DateTime(2022, 9, 2, 6, 59, 22, 563, DateTimeKind.Local).AddTicks(4139)
                        },
                        new
                        {
                            Id = new Guid("2892eda1-87aa-4938-b979-4848a8710686"),
                            CabRideId = new Guid("1e1c7fb6-7997-4297-b829-ee818635329a"),
                            StatusId = new Guid("b370867a-2261-42eb-9b7b-2fd6bd26a224"),
                            StatusTime = new DateTime(2022, 7, 18, 12, 19, 14, 623, DateTimeKind.Local).AddTicks(6251)
                        },
                        new
                        {
                            Id = new Guid("c8e8b7e3-139f-4313-a7a1-1599d115ed5c"),
                            CabRideId = new Guid("d3db81d3-4e36-45ca-b8ea-51495ecb91dd"),
                            StatusId = new Guid("1767f2fd-a497-4162-a34e-23ecbeb7b74d"),
                            StatusTime = new DateTime(2023, 2, 13, 4, 5, 53, 249, DateTimeKind.Local).AddTicks(2758)
                        },
                        new
                        {
                            Id = new Guid("8756319a-382c-4ff1-ae46-9ed9917bd243"),
                            CabRideId = new Guid("e5a32545-6ae7-4957-a4e4-8e7ef3655c89"),
                            StatusId = new Guid("1767f2fd-a497-4162-a34e-23ecbeb7b74d"),
                            StatusTime = new DateTime(2022, 9, 17, 16, 23, 9, 282, DateTimeKind.Local).AddTicks(3496)
                        },
                        new
                        {
                            Id = new Guid("257d63e5-7c28-4e18-80a8-cc086c2dc22a"),
                            CabRideId = new Guid("e5a32545-6ae7-4957-a4e4-8e7ef3655c89"),
                            StatusId = new Guid("41f91944-6ad8-493f-bcc5-5f7b4dc342f2"),
                            StatusTime = new DateTime(2022, 9, 6, 6, 30, 15, 439, DateTimeKind.Local).AddTicks(2653)
                        },
                        new
                        {
                            Id = new Guid("bf7c25c7-1aba-4b54-8ad9-4aa7f1916f3b"),
                            CabRideId = new Guid("1e1c7fb6-7997-4297-b829-ee818635329a"),
                            StatusId = new Guid("b370867a-2261-42eb-9b7b-2fd6bd26a224"),
                            StatusTime = new DateTime(2023, 4, 13, 8, 2, 24, 959, DateTimeKind.Local).AddTicks(1731)
                        },
                        new
                        {
                            Id = new Guid("76407e05-9a1b-47d3-b9ce-d7900510160c"),
                            CabRideId = new Guid("7a2cb453-04e3-47ab-816f-ee492ed8aed8"),
                            StatusId = new Guid("41f91944-6ad8-493f-bcc5-5f7b4dc342f2"),
                            StatusTime = new DateTime(2023, 3, 20, 7, 10, 46, 746, DateTimeKind.Local).AddTicks(8334)
                        },
                        new
                        {
                            Id = new Guid("3e2ffe92-880b-4dfa-b50a-c1857a9afca2"),
                            CabRideId = new Guid("7a2cb453-04e3-47ab-816f-ee492ed8aed8"),
                            StatusId = new Guid("41f91944-6ad8-493f-bcc5-5f7b4dc342f2"),
                            StatusTime = new DateTime(2022, 9, 20, 22, 3, 20, 677, DateTimeKind.Local).AddTicks(6714)
                        },
                        new
                        {
                            Id = new Guid("2684d3ee-3df4-4709-b786-69852fa58941"),
                            CabRideId = new Guid("e5a32545-6ae7-4957-a4e4-8e7ef3655c89"),
                            StatusId = new Guid("1767f2fd-a497-4162-a34e-23ecbeb7b74d"),
                            StatusTime = new DateTime(2023, 1, 6, 18, 50, 28, 362, DateTimeKind.Local).AddTicks(5665)
                        },
                        new
                        {
                            Id = new Guid("04312449-7acc-489f-8fc4-589449b47ab0"),
                            CabRideId = new Guid("e5a32545-6ae7-4957-a4e4-8e7ef3655c89"),
                            StatusId = new Guid("1767f2fd-a497-4162-a34e-23ecbeb7b74d"),
                            StatusTime = new DateTime(2022, 10, 4, 14, 58, 34, 140, DateTimeKind.Local).AddTicks(7374)
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrivingLicenceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Working")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("driver", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe838614-479d-4e6e-bc00-f8588a755e63"),
                            BirthDate = new DateTime(2022, 10, 1, 13, 23, 9, 742, DateTimeKind.Local).AddTicks(7396),
                            DrivingLicenceNumber = "htca3beidd",
                            ExpiryDate = new DateTime(2022, 10, 18, 13, 21, 55, 687, DateTimeKind.Local).AddTicks(6052),
                            FirstName = "Andrew",
                            LastName = "Douglas",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("dd1feacf-b90b-4dfe-a483-98f42a243678"),
                            BirthDate = new DateTime(2022, 8, 5, 22, 40, 19, 544, DateTimeKind.Local).AddTicks(4852),
                            DrivingLicenceNumber = "rv6rkzl43y",
                            ExpiryDate = new DateTime(2022, 11, 24, 12, 48, 38, 964, DateTimeKind.Local).AddTicks(2240),
                            FirstName = "Kurt",
                            LastName = "Gerlach",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("f260175a-eef4-4c2a-ba5f-eecc45d64ead"),
                            BirthDate = new DateTime(2022, 7, 10, 12, 5, 24, 168, DateTimeKind.Local).AddTicks(1111),
                            DrivingLicenceNumber = "n482dx19gv",
                            ExpiryDate = new DateTime(2022, 7, 8, 20, 35, 52, 352, DateTimeKind.Local).AddTicks(7770),
                            FirstName = "Carlos",
                            LastName = "Rohan",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("5eccdfb4-df50-4d1e-89c7-5d498379efe9"),
                            BirthDate = new DateTime(2022, 8, 7, 3, 33, 10, 294, DateTimeKind.Local).AddTicks(89),
                            DrivingLicenceNumber = "az0jmqisw3",
                            ExpiryDate = new DateTime(2023, 2, 28, 19, 10, 17, 48, DateTimeKind.Local).AddTicks(4802),
                            FirstName = "Adam",
                            LastName = "Brekke",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("fbee05e4-66de-47b3-bf76-1743e840f3e2"),
                            BirthDate = new DateTime(2022, 10, 6, 22, 16, 13, 597, DateTimeKind.Local).AddTicks(7030),
                            DrivingLicenceNumber = "o0yeves5sf",
                            ExpiryDate = new DateTime(2022, 11, 15, 5, 38, 47, 931, DateTimeKind.Local).AddTicks(5022),
                            FirstName = "Edna",
                            LastName = "Deckow",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("a5612006-d22a-42b4-aa89-0bc0f558f02d"),
                            BirthDate = new DateTime(2022, 9, 22, 13, 41, 51, 988, DateTimeKind.Local).AddTicks(8534),
                            DrivingLicenceNumber = "xj4uoz8rpg",
                            ExpiryDate = new DateTime(2022, 7, 6, 23, 50, 2, 883, DateTimeKind.Local).AddTicks(7853),
                            FirstName = "Allison",
                            LastName = "Osinski",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("fc322e56-7a6b-4bc6-ae32-342759e78b38"),
                            BirthDate = new DateTime(2023, 4, 15, 17, 9, 38, 328, DateTimeKind.Local).AddTicks(3690),
                            DrivingLicenceNumber = "v9csxei7ho",
                            ExpiryDate = new DateTime(2023, 5, 26, 23, 54, 1, 357, DateTimeKind.Local).AddTicks(7340),
                            FirstName = "Mary",
                            LastName = "Goldner",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("34f2f031-8967-459a-9597-754948212054"),
                            BirthDate = new DateTime(2022, 7, 30, 14, 55, 6, 842, DateTimeKind.Local).AddTicks(9355),
                            DrivingLicenceNumber = "jz8xqqd0xf",
                            ExpiryDate = new DateTime(2022, 12, 12, 12, 40, 4, 257, DateTimeKind.Local).AddTicks(2829),
                            FirstName = "Ed",
                            LastName = "Mayer",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("c493f7a1-2266-4316-be86-886b8c898039"),
                            BirthDate = new DateTime(2023, 4, 23, 11, 52, 56, 653, DateTimeKind.Local).AddTicks(7124),
                            DrivingLicenceNumber = "so8wl9lv9a",
                            ExpiryDate = new DateTime(2023, 3, 6, 2, 16, 44, 694, DateTimeKind.Local).AddTicks(1097),
                            FirstName = "Shannon",
                            LastName = "Gutmann",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("550fdd9b-e135-4a61-88d7-ce81d27a71d4"),
                            BirthDate = new DateTime(2023, 5, 3, 14, 10, 24, 518, DateTimeKind.Local).AddTicks(9579),
                            DrivingLicenceNumber = "mqp9jkmd7y",
                            ExpiryDate = new DateTime(2022, 10, 12, 4, 35, 36, 324, DateTimeKind.Local).AddTicks(8562),
                            FirstName = "Krista",
                            LastName = "Howell",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("83849adb-75d5-4ad7-a33d-19ebd37c555b"),
                            BirthDate = new DateTime(2022, 9, 11, 16, 20, 6, 942, DateTimeKind.Local).AddTicks(9861),
                            DrivingLicenceNumber = "1v9x7g8clc",
                            ExpiryDate = new DateTime(2022, 10, 6, 22, 6, 20, 916, DateTimeKind.Local).AddTicks(31),
                            FirstName = "Amanda",
                            LastName = "Murazik",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("84028a3e-ad50-40ef-a693-3355a9ae489b"),
                            BirthDate = new DateTime(2022, 8, 31, 12, 20, 15, 709, DateTimeKind.Local).AddTicks(815),
                            DrivingLicenceNumber = "z9tvcl1ken",
                            ExpiryDate = new DateTime(2023, 4, 29, 3, 48, 2, 220, DateTimeKind.Local).AddTicks(60),
                            FirstName = "Homer",
                            LastName = "Cassin",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("59dae223-0fa4-4423-bc47-2945202ad8d5"),
                            BirthDate = new DateTime(2022, 8, 25, 1, 57, 5, 439, DateTimeKind.Local).AddTicks(7820),
                            DrivingLicenceNumber = "6aczjev5wo",
                            ExpiryDate = new DateTime(2022, 12, 20, 22, 55, 58, 709, DateTimeKind.Local).AddTicks(4687),
                            FirstName = "Jeffery",
                            LastName = "Hirthe",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("660c6427-e57c-40b9-b6e1-c562a8f61171"),
                            BirthDate = new DateTime(2022, 9, 7, 20, 8, 44, 897, DateTimeKind.Local).AddTicks(3584),
                            DrivingLicenceNumber = "lja8v4bu5j",
                            ExpiryDate = new DateTime(2022, 6, 11, 11, 51, 12, 480, DateTimeKind.Local).AddTicks(3294),
                            FirstName = "Doreen",
                            LastName = "Cronin",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("e9c64a92-4625-496a-b884-375b4b340241"),
                            BirthDate = new DateTime(2022, 10, 12, 11, 43, 1, 710, DateTimeKind.Local).AddTicks(8428),
                            DrivingLicenceNumber = "vi1sgdi9ba",
                            ExpiryDate = new DateTime(2023, 2, 7, 15, 12, 30, 808, DateTimeKind.Local).AddTicks(4734),
                            FirstName = "Sean",
                            LastName = "Crooks",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("d2ad13e5-f56e-4c7a-9744-c7e9d57c7ada"),
                            BirthDate = new DateTime(2023, 4, 13, 10, 47, 1, 913, DateTimeKind.Local).AddTicks(6713),
                            DrivingLicenceNumber = "4o9nm6t1mn",
                            ExpiryDate = new DateTime(2022, 11, 14, 10, 4, 3, 522, DateTimeKind.Local).AddTicks(8895),
                            FirstName = "Mathew",
                            LastName = "Gleason",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("0ea3fd5e-b301-4786-838d-74eec08f11c2"),
                            BirthDate = new DateTime(2022, 7, 31, 21, 56, 31, 506, DateTimeKind.Local).AddTicks(9919),
                            DrivingLicenceNumber = "ap9rv4yuzj",
                            ExpiryDate = new DateTime(2023, 5, 10, 4, 14, 44, 410, DateTimeKind.Local).AddTicks(8393),
                            FirstName = "Marion",
                            LastName = "Rogahn",
                            Working = true
                        },
                        new
                        {
                            Id = new Guid("c561456d-f4e5-447c-b072-c1eb19ed4bbe"),
                            BirthDate = new DateTime(2022, 12, 7, 4, 43, 43, 815, DateTimeKind.Local).AddTicks(6420),
                            DrivingLicenceNumber = "cfizr46qur",
                            ExpiryDate = new DateTime(2022, 7, 5, 12, 35, 9, 736, DateTimeKind.Local).AddTicks(9674),
                            FirstName = "Yolanda",
                            LastName = "Heidenreich",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("ce2133e9-2a91-4a2f-92c8-20c3cad83c1d"),
                            BirthDate = new DateTime(2023, 2, 18, 8, 5, 10, 402, DateTimeKind.Local).AddTicks(7788),
                            DrivingLicenceNumber = "x8z4m1mph6",
                            ExpiryDate = new DateTime(2023, 2, 1, 17, 8, 32, 79, DateTimeKind.Local).AddTicks(7036),
                            FirstName = "James",
                            LastName = "Funk",
                            Working = false
                        },
                        new
                        {
                            Id = new Guid("719056f8-c74b-4eb6-963e-95966666271c"),
                            BirthDate = new DateTime(2022, 12, 16, 22, 32, 8, 323, DateTimeKind.Local).AddTicks(7542),
                            DrivingLicenceNumber = "q9imt49gw3",
                            ExpiryDate = new DateTime(2023, 4, 27, 13, 56, 53, 434, DateTimeKind.Local).AddTicks(3460),
                            FirstName = "Sara",
                            LastName = "Parker",
                            Working = false
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.PaymentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("payment_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("985e82da-34d5-4312-b988-f61109671c7c"),
                            NameType = "готівка"
                        },
                        new
                        {
                            Id = new Guid("b5d27d34-a8db-42e7-ab90-dd186288dd4e"),
                            NameType = "карта"
                        },
                        new
                        {
                            Id = new Guid("0eff2385-86f2-4113-bb02-3b9d382083db"),
                            NameType = "карта"
                        },
                        new
                        {
                            Id = new Guid("ecdec2c7-1c74-4d17-86b0-f2df3252774b"),
                            NameType = "карта"
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ShiftEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CabId");

                    b.HasIndex("DriverId");

                    b.ToTable("shift", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d76dd061-1f7a-4ba8-be7f-6262e75ae6dc"),
                            CabId = new Guid("c5165210-6c72-440a-9f8e-f3e9808cb391"),
                            DriverId = new Guid("34f2f031-8967-459a-9597-754948212054"),
                            ShiftEndTime = new DateTime(2022, 10, 23, 18, 13, 2, 667, DateTimeKind.Local).AddTicks(9342),
                            ShiftStartTime = new DateTime(2022, 10, 23, 18, 56, 25, 410, DateTimeKind.Local).AddTicks(2771)
                        },
                        new
                        {
                            Id = new Guid("d827f272-77b3-4fdf-9011-d6754478e708"),
                            CabId = new Guid("17058a79-c06f-4954-ac65-d817cb5109cc"),
                            DriverId = new Guid("fc322e56-7a6b-4bc6-ae32-342759e78b38"),
                            ShiftEndTime = new DateTime(2023, 6, 5, 3, 6, 11, 125, DateTimeKind.Local).AddTicks(4615),
                            ShiftStartTime = new DateTime(2023, 6, 5, 12, 43, 59, 994, DateTimeKind.Local).AddTicks(6764)
                        },
                        new
                        {
                            Id = new Guid("5d31f987-4754-4a41-851c-bc2c56e7b812"),
                            CabId = new Guid("d88926df-d274-4105-b2e0-8d0f35233ab6"),
                            DriverId = new Guid("a5612006-d22a-42b4-aa89-0bc0f558f02d"),
                            ShiftEndTime = new DateTime(2022, 7, 25, 15, 6, 3, 445, DateTimeKind.Local).AddTicks(9941),
                            ShiftStartTime = new DateTime(2022, 7, 25, 19, 43, 59, 623, DateTimeKind.Local).AddTicks(6633)
                        },
                        new
                        {
                            Id = new Guid("1c5dfd11-6e2c-47a3-bee0-81640bc27c27"),
                            CabId = new Guid("17058a79-c06f-4954-ac65-d817cb5109cc"),
                            DriverId = new Guid("f260175a-eef4-4c2a-ba5f-eecc45d64ead"),
                            ShiftEndTime = new DateTime(2022, 10, 22, 9, 44, 54, 842, DateTimeKind.Local).AddTicks(3127),
                            ShiftStartTime = new DateTime(2022, 10, 22, 21, 23, 37, 489, DateTimeKind.Local).AddTicks(7703)
                        },
                        new
                        {
                            Id = new Guid("3e900077-4087-4b66-8578-9dd2b562fb51"),
                            CabId = new Guid("49fabbc3-d04d-4317-8337-dc48ebe4f82a"),
                            DriverId = new Guid("c493f7a1-2266-4316-be86-886b8c898039"),
                            ShiftEndTime = new DateTime(2023, 3, 11, 2, 40, 15, 535, DateTimeKind.Local).AddTicks(5896),
                            ShiftStartTime = new DateTime(2023, 3, 11, 3, 16, 43, 183, DateTimeKind.Local).AddTicks(2611)
                        },
                        new
                        {
                            Id = new Guid("1699f09b-0518-449c-a5d3-ccd2c9460d64"),
                            CabId = new Guid("5bda64d4-1d57-414f-a61c-69f09cdc2182"),
                            DriverId = new Guid("dd1feacf-b90b-4dfe-a483-98f42a243678"),
                            ShiftEndTime = new DateTime(2022, 9, 22, 11, 54, 30, 802, DateTimeKind.Local).AddTicks(5453),
                            ShiftStartTime = new DateTime(2022, 9, 22, 20, 32, 17, 938, DateTimeKind.Local).AddTicks(5045)
                        },
                        new
                        {
                            Id = new Guid("e68a650b-26e9-4e44-be09-1d50833329d0"),
                            CabId = new Guid("d88926df-d274-4105-b2e0-8d0f35233ab6"),
                            DriverId = new Guid("fbee05e4-66de-47b3-bf76-1743e840f3e2"),
                            ShiftEndTime = new DateTime(2023, 2, 27, 11, 22, 4, 201, DateTimeKind.Local).AddTicks(2348),
                            ShiftStartTime = new DateTime(2023, 2, 27, 17, 59, 22, 180, DateTimeKind.Local).AddTicks(9535)
                        },
                        new
                        {
                            Id = new Guid("1a59f6e7-ba15-4f60-9ba1-210a1641bc99"),
                            CabId = new Guid("4e0209c1-f9b5-4612-9acd-d68d16935549"),
                            DriverId = new Guid("5eccdfb4-df50-4d1e-89c7-5d498379efe9"),
                            ShiftEndTime = new DateTime(2023, 3, 21, 6, 23, 27, 712, DateTimeKind.Local).AddTicks(3651),
                            ShiftStartTime = new DateTime(2023, 3, 21, 13, 5, 16, 109, DateTimeKind.Local).AddTicks(3886)
                        },
                        new
                        {
                            Id = new Guid("8633f0ad-bb06-4172-b77e-5a5f4ff5c6f0"),
                            CabId = new Guid("49fabbc3-d04d-4317-8337-dc48ebe4f82a"),
                            DriverId = new Guid("34f2f031-8967-459a-9597-754948212054"),
                            ShiftEndTime = new DateTime(2023, 2, 25, 6, 51, 35, 2, DateTimeKind.Local).AddTicks(3095),
                            ShiftStartTime = new DateTime(2023, 2, 25, 8, 3, 5, 593, DateTimeKind.Local).AddTicks(9299)
                        },
                        new
                        {
                            Id = new Guid("be5527a5-b550-4682-8f1b-5abbe1e62dc9"),
                            CabId = new Guid("17058a79-c06f-4954-ac65-d817cb5109cc"),
                            DriverId = new Guid("34f2f031-8967-459a-9597-754948212054"),
                            ShiftEndTime = new DateTime(2023, 4, 23, 17, 1, 30, 289, DateTimeKind.Local).AddTicks(9670),
                            ShiftStartTime = new DateTime(2023, 4, 24, 1, 37, 43, 842, DateTimeKind.Local).AddTicks(8288)
                        },
                        new
                        {
                            Id = new Guid("6870ac8f-13a1-424f-bbda-ae8533e892e2"),
                            CabId = new Guid("b99c126b-d873-425a-a056-41ed749a9cc8"),
                            DriverId = new Guid("719056f8-c74b-4eb6-963e-95966666271c"),
                            ShiftEndTime = new DateTime(2023, 2, 2, 4, 53, 29, 943, DateTimeKind.Local).AddTicks(5139),
                            ShiftStartTime = new DateTime(2023, 2, 2, 5, 38, 8, 980, DateTimeKind.Local).AddTicks(2621)
                        },
                        new
                        {
                            Id = new Guid("6601fc2b-30e8-4aa9-b84d-655484c7d375"),
                            CabId = new Guid("aa8519ef-a257-4cd2-8fdd-f506ef2da9e3"),
                            DriverId = new Guid("719056f8-c74b-4eb6-963e-95966666271c"),
                            ShiftEndTime = new DateTime(2022, 6, 13, 21, 8, 56, 212, DateTimeKind.Local).AddTicks(3965),
                            ShiftStartTime = new DateTime(2022, 6, 14, 2, 39, 57, 78, DateTimeKind.Local).AddTicks(9219)
                        },
                        new
                        {
                            Id = new Guid("3453203c-ed99-4fb1-9f36-62a4b0f788cf"),
                            CabId = new Guid("3a7420d0-8686-4dc4-b321-d0dc879c452c"),
                            DriverId = new Guid("59dae223-0fa4-4423-bc47-2945202ad8d5"),
                            ShiftEndTime = new DateTime(2022, 7, 12, 15, 19, 27, 139, DateTimeKind.Local).AddTicks(5948),
                            ShiftStartTime = new DateTime(2022, 7, 12, 17, 52, 49, 83, DateTimeKind.Local).AddTicks(5076)
                        },
                        new
                        {
                            Id = new Guid("9b94d825-fd94-43e3-997d-cde536917e52"),
                            CabId = new Guid("aa8519ef-a257-4cd2-8fdd-f506ef2da9e3"),
                            DriverId = new Guid("84028a3e-ad50-40ef-a693-3355a9ae489b"),
                            ShiftEndTime = new DateTime(2022, 6, 20, 22, 53, 19, 128, DateTimeKind.Local).AddTicks(321),
                            ShiftStartTime = new DateTime(2022, 6, 21, 1, 57, 5, 138, DateTimeKind.Local).AddTicks(5270)
                        },
                        new
                        {
                            Id = new Guid("416d4501-2004-4d48-ac1a-c83422a31563"),
                            CabId = new Guid("334a5e53-989c-4486-9d07-d6ffccb609f8"),
                            DriverId = new Guid("c561456d-f4e5-447c-b072-c1eb19ed4bbe"),
                            ShiftEndTime = new DateTime(2022, 8, 14, 4, 13, 26, 856, DateTimeKind.Local).AddTicks(8578),
                            ShiftStartTime = new DateTime(2022, 8, 14, 8, 50, 47, 725, DateTimeKind.Local).AddTicks(2643)
                        },
                        new
                        {
                            Id = new Guid("6405f468-ab27-4777-b47f-6f4279823e87"),
                            CabId = new Guid("bdceb7ab-4b1b-46e5-8467-80afe6bcb0a2"),
                            DriverId = new Guid("83849adb-75d5-4ad7-a33d-19ebd37c555b"),
                            ShiftEndTime = new DateTime(2023, 3, 21, 2, 28, 23, 106, DateTimeKind.Local).AddTicks(6305),
                            ShiftStartTime = new DateTime(2023, 3, 21, 10, 34, 27, 472, DateTimeKind.Local).AddTicks(6232)
                        },
                        new
                        {
                            Id = new Guid("7494d324-b215-48e4-828b-c0216d232b6d"),
                            CabId = new Guid("334a5e53-989c-4486-9d07-d6ffccb609f8"),
                            DriverId = new Guid("83849adb-75d5-4ad7-a33d-19ebd37c555b"),
                            ShiftEndTime = new DateTime(2023, 2, 27, 22, 46, 18, 782, DateTimeKind.Local).AddTicks(1908),
                            ShiftStartTime = new DateTime(2023, 2, 28, 8, 35, 20, 365, DateTimeKind.Local).AddTicks(5318)
                        },
                        new
                        {
                            Id = new Guid("cc76a5f4-115f-471e-a6b6-077916b316c5"),
                            CabId = new Guid("3a7420d0-8686-4dc4-b321-d0dc879c452c"),
                            DriverId = new Guid("d2ad13e5-f56e-4c7a-9744-c7e9d57c7ada"),
                            ShiftEndTime = new DateTime(2022, 11, 30, 7, 59, 1, 299, DateTimeKind.Local).AddTicks(8015),
                            ShiftStartTime = new DateTime(2022, 11, 30, 19, 43, 16, 643, DateTimeKind.Local).AddTicks(6967)
                        },
                        new
                        {
                            Id = new Guid("453baad2-d6b8-449c-87ad-1e30755ce5f0"),
                            CabId = new Guid("da917976-0cee-4ea9-b36d-2d4aedc34f37"),
                            DriverId = new Guid("59dae223-0fa4-4423-bc47-2945202ad8d5"),
                            ShiftEndTime = new DateTime(2022, 10, 31, 12, 23, 35, 790, DateTimeKind.Local).AddTicks(439),
                            ShiftStartTime = new DateTime(2022, 10, 31, 18, 36, 13, 469, DateTimeKind.Local).AddTicks(5715)
                        },
                        new
                        {
                            Id = new Guid("992c970b-879a-4104-8659-da1ff5a97ee8"),
                            CabId = new Guid("3a7420d0-8686-4dc4-b321-d0dc879c452c"),
                            DriverId = new Guid("d2ad13e5-f56e-4c7a-9744-c7e9d57c7ada"),
                            ShiftEndTime = new DateTime(2022, 7, 22, 10, 21, 12, 383, DateTimeKind.Local).AddTicks(8516),
                            ShiftStartTime = new DateTime(2022, 7, 22, 20, 45, 31, 763, DateTimeKind.Local).AddTicks(8586)
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1322b7a1-90bd-475f-bdc7-30a308b4bb61"),
                            StatusName = "В дорозі"
                        },
                        new
                        {
                            Id = new Guid("154ea15b-a524-40a6-89ff-2cd5efb69aed"),
                            StatusName = "В дорозі"
                        },
                        new
                        {
                            Id = new Guid("51b4484f-6d43-4dfd-bf70-6febcdbb2522"),
                            StatusName = "Подорож закінчена"
                        },
                        new
                        {
                            Id = new Guid("1767f2fd-a497-4162-a34e-23ecbeb7b74d"),
                            StatusName = "Очікує"
                        },
                        new
                        {
                            Id = new Guid("41f91944-6ad8-493f-bcc5-5f7b4dc342f2"),
                            StatusName = "Подорож закінчена"
                        },
                        new
                        {
                            Id = new Guid("b370867a-2261-42eb-9b7b-2fd6bd26a224"),
                            StatusName = "Очікує"
                        });
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.CabRide", b =>
                {
                    b.HasOne("Taxi_Managment_System_DAL.Models.PaymentType", "PaymentType")
                        .WithMany("CabRides")
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxi_Managment_System_DAL.Models.Shift", "Shift")
                        .WithMany("CabRides")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.CabRideStatus", b =>
                {
                    b.HasOne("Taxi_Managment_System_DAL.Models.CabRide", "CabRide")
                        .WithMany("CabRideStatuses")
                        .HasForeignKey("CabRideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxi_Managment_System_DAL.Models.Status", "Status")
                        .WithMany("CabRideStatuses")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CabRide");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Shift", b =>
                {
                    b.HasOne("Taxi_Managment_System_DAL.Models.Cab", "Cab")
                        .WithMany("Shifts")
                        .HasForeignKey("CabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taxi_Managment_System_DAL.Models.Driver", "Driver")
                        .WithMany("Shifts")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cab");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Cab", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.CabRide", b =>
                {
                    b.Navigation("CabRideStatuses");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Driver", b =>
                {
                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.PaymentType", b =>
                {
                    b.Navigation("CabRides");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Shift", b =>
                {
                    b.Navigation("CabRides");
                });

            modelBuilder.Entity("Taxi_Managment_System_DAL.Models.Status", b =>
                {
                    b.Navigation("CabRideStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
